version: "1.0"

dns:
  resolvers:
    - 1.1.1.1      # Cloudflare DNS
    - 8.8.8.8      # Google DNS
    - 9.9.9.9      # Quad9 DNS
    - 1.0.0.1      # Cloudflare DNS (secondary)
    - 8.8.4.4      # Google DNS (secondary)
    - 208.67.222.222 # OpenDNS
    - 208.67.220.220 # OpenDNS (secondary)
    - 185.228.168.168 # CleanBrowsing
    - 185.228.169.168 # CleanBrowsing (secondary)
  timeout: 30
  noRecurse: false