version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: osintdb
      POSTGRES_USER: osintuser
      POSTGRES_PASSWORD: osintpass
    ports:
      - "5433:5432"
    volumes:
      - postgres-osint-data:/var/lib/postgresql/osint/data
    networks:
      - osint-net

  amass:
    image: caffix/amass
    container_name: amass
    stdin_open: true
    tty: true
    volumes:
      - ./amass/config:/config/amass
    entrypoint: tail -f /dev/null
    networks:
      - osint-net

volumes:
  postgres-osint-data:

networks:
  osint-net:
    driver: bridge
